#!/bin/bash

# Confluence 智能配置检测测试脚本

echo "=========================================="
echo "Confluence 智能配置检测功能测试"
echo "=========================================="
echo ""

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}测试场景 1: 无预配置${NC}"
echo "-----------------------------------"
echo "1. 确保账户设置中没有 Confluence 配置"
echo "2. 打开导入模态框"
echo ""
echo -e "${YELLOW}预期结果：${NC}"
echo "✓ 显示蓝色提示：'输入您的 Confluence URL 和个人访问令牌以直接导入文档'"
echo "✓ 显示 '保存以供将来使用' 链接"
echo "✓ 显示 Confluence URL 输入框（必填）"
echo "✓ 显示 Personal Access Token 输入框（必填）"
echo "✓ 显示 Confluence Page URL 输入框（必填）"
echo "✓ 显示 'Include child pages' 开关"
echo ""
read -p "按回车继续测试场景 2..."
echo ""

echo -e "${BLUE}测试场景 2: 有预配置${NC}"
echo "-----------------------------------"
echo "1. 访问 设置 → 账户 → 我的资料"
echo "2. 找到 'Confluence Integration' 部分"
echo "3. 输入 Confluence URL 和 Token"
echo "4. 点击 '保存配置'"
echo "5. 返回文档库，打开导入模态框"
echo ""
echo -e "${YELLOW}预期结果：${NC}"
echo "✓ 显示绿色提示：'使用已保存的 Confluence 配置'"
echo "✓ 显示 '更改设置' 链接"
echo "✓ 不显示 Confluence URL 输入框"
echo "✓ 不显示 Personal Access Token 输入框"
echo "✓ 只显示 Confluence Page URL 输入框（必填）"
echo "✓ 显示 'Include child pages' 开关"
echo ""
read -p "按回车继续测试场景 3..."
echo ""

echo -e "${BLUE}测试场景 3: 使用预配置导入${NC}"
echo "-----------------------------------"
echo "1. 确保已有预配置（场景 2）"
echo "2. 在导入模态框中只输入页面 URL"
echo "3. 点击 '导入'"
echo ""
echo -e "${YELLOW}预期结果：${NC}"
echo "✓ 导入成功开始"
echo "✓ 显示成功通知"
echo "✓ 页面内容成功导入"
echo "✓ 服务器日志显示 'Using saved Confluence configuration'"
echo ""
read -p "按回车继续测试场景 4..."
echo ""

echo -e "${BLUE}测试场景 4: 临时导入（无预配置）${NC}"
echo "-----------------------------------"
echo "1. 删除账户设置中的 Confluence 配置"
echo "2. 打开导入模态框"
echo "3. 输入所有字段（URL、Token、页面 URL）"
echo "4. 点击 '导入'"
echo ""
echo -e "${YELLOW}预期结果：${NC}"
echo "✓ 导入成功开始"
echo "✓ 显示成功通知"
echo "✓ 页面内容成功导入"
echo "✓ 配置不会被保存"
echo ""
read -p "按回车继续测试场景 5..."
echo ""

echo -e "${BLUE}测试场景 5: 表单验证${NC}"
echo "-----------------------------------"
echo "测试 5.1: 无预配置时留空必填字段"
echo "  ✓ Confluence URL 为空 → 显示 'Confluence URL is required'"
echo "  ✓ Access Token 为空 → 显示 'Access token is required'"
echo "  ✓ Page URL 为空 → 显示 'Page URL is required'"
echo ""
echo "测试 5.2: 有预配置时留空页面 URL"
echo "  ✓ Page URL 为空 → 显示 'Page URL is required'"
echo "  ✓ 不验证 URL 和 Token（因为使用保存的配置）"
echo ""
echo "测试 5.3: URL 格式验证"
echo "  ✓ URL 不以 http 开头 → 显示 'Please enter a valid URL'"
echo "  ✓ 页面 URL 格式错误 → 显示 'Please enter a valid Confluence page URL'"
echo ""
read -p "按回车继续测试场景 6..."
echo ""

echo -e "${BLUE}测试场景 6: 链接跳转${NC}"
echo "-----------------------------------"
echo "1. 点击 '更改设置' 链接"
echo "   ✓ 跳转到 /settings/account/profile"
echo ""
echo "2. 点击 '保存以供将来使用' 链接"
echo "   ✓ 跳转到 /settings/account/profile"
echo ""
read -p "按回车查看总结..."
echo ""

echo "=========================================="
echo "功能验证清单"
echo "=========================================="
echo ""
echo "前端功能："
echo "  □ 自动检测配置状态"
echo "  □ 有配置时隐藏 URL 和 Token 输入框"
echo "  □ 无配置时显示完整表单"
echo "  □ 正确的提示信息和颜色"
echo "  □ 链接正确跳转"
echo "  □ 表单验证正确"
echo ""
echo "后端功能："
echo "  □ 接收可选的 URL 和 Token"
echo "  □ 自动使用保存的配置"
echo "  □ 正确的错误处理"
echo "  □ 详细的日志记录"
echo ""
echo "用户体验："
echo "  □ 预配置后快速导入"
echo "  □ 支持临时导入"
echo "  □ 清晰的引导提示"
echo "  □ 流畅的操作流程"
echo ""

echo -e "${GREEN}测试完成！${NC}"
echo ""
echo "如果所有场景都通过，智能配置检测功能已正确实现。"
